### ISSUE TITLE
Location of communicationinjector.js

### ISSUE THREAD

**Issue by MineshS** [episerver/cms-saas-vercel-demo#16]
Hi @remkoj 

I know this boilerplate is specifically for SaaS but I am trying to use it on PaaS, the communicationinjector.js in both versions seem to be slightly different 

On PaaS I have had to set to : `${dxpUrl}ui/cms/latest/clientresources/epi-cms/communicationinjector.js`, 
Which actually redirects too  : https://localhost:5000/Util/javascript/communicationinjector.js

On SaaS and in your package it seems like the location is : ${dxpUrl}/ui/CMS/latest/clientresources/communicationinjector.js

I'm worried if I was to Utilize the NPM packages I will not be able to override this value. Can I have some feedback on this. 

Minesh

**Comment by remkoj** [comment]
Hi @MineshS,

I will release a new version of the packages this week (v1.0.5) that will both use the new URL (/util/javascript/communicationinjector.js) as well as provide you with the means to override the new URL when creating the In Context Edit pages. These changes are already in the v2 branch, but I will back-port them to v1.0.5.

**Comment by MineshS** [comment]
Thank you so much @remkoj  Our frontend team are currently just refactoring to remove the Packages folder and utilize NPM Packages instead will let you know how we get on

**Comment by MineshS** [comment]
hey @remkoj  any update on when v1.0.5 will be pushed

**Comment by remkoj** [comment]
This has been released for both 1.x and 2.x versions of the packages.
