### ISSUE TITLE
When attempting to upload the data file I'm getting the error ""Timed out, or max file size exceeded""!

### ISSUE THREAD

**Issue by ScottReed** [episerver/cms-saas-vercel-demo#2]
![image (1)](https://github.com/episerver/cms-saas-vercel-demo/assets/1773620/94cc9d09-8d86-4f7a-83cb-99b0b5afab29)

I'm getting "Timed out, or max file size exceeded" when trying to use the data file as part of the first step!

**Comment by remkoj** [comment]
@ScottReed: This error seems to be related to the CMS instance, can you put your question in the slack channel for support with importing content.

**Comment by ScottReed** [comment]
Sure, I thought you were Optimizely working on the SaaS product so expected you'd have some idea why this would be failing on the instance configuration. As the reference demo if this isn't working as expected there should be some note or something on the setup but I'll raise it on slack too

**Comment by jon419** [comment]
Hey @scottreed - did they ever help you on Slack.  It is now 2025 and im trying to import the content and I am getting the same error.
