### ISSUE TITLE
Issue with RichTextFormat.Structured and RichTextFormat.HtmlAndStructured

### ISSUE THREAD

**Issue by MattisOlsson** [episerver/cms-saas-vercel-demo#5]
Hi!

I have been playing around with this and have found one issue:

- When using `RichTextFormat.Structured` or `RichTextFormat.HtmlAndStructured`, the Structure field in the response from the Apollo Client is always null. However, when querying from the GraphiQL UI in the CMS, I can see it has values.
 
Do you perhaps have any information regarding this or some workaround?

EDIT: I can see that an error is thrown when using the getContentById function and when a block fragment contains the Structure field:

![image](https://github.com/episerver/cms-saas-vercel-demo/assets/5345333/12e21920-95d4-4399-a7aa-b0928f119f32)

**Comment by remkoj** [comment]
This demo site follows the capabilities and configuration of SaaS CMS, which has some new features (such as VisualBuilder and APIs) ahead of PaaS CMS. Once these features are available for PaaS CMS, you may configure it to match the configuration of SaaS CMS.
