### ISSUE TITLE
Heading levels in Heading's Style area need to be tweaked (3,4,5 are the same)

### ISSUE THREAD

**Issue by petriisola** [episerver/cms-saas-vercel-demo#67]
![image](https://github.com/user-attachments/assets/56290692-a756-4476-832d-9e50b4b9e25b)

**Comment by remkoj** [comment]
@petriisola Please review on the syles enhancements branch

**Comment by petriisola** [comment]
Looks more like it now:
![image](https://github.com/user-attachments/assets/413eab5e-07b1-4b3f-b286-d99861f3bb93)
